name: Selenium Pytest CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Test Login
        env:
          CI: true
        run: pytest tests/test_login.py -v

      - name: Test Register
        env:
          CI: true
        run: pytest tests/test_register.py -v

      - name: Test Search
        env:
          CI: true
        run: pytest tests/test_search.py -v

      - name: Test Order
        env:
          CI: true
        run: pytest tests/test_order.py -v
